# Working with RNA

```{block2, type='note'}
Contamination with exogenous RNAse usually occurs because of buffers that have been contaminated with microorganisms (due to shoddy aseptic technique) or from automatic pipettors.

```

## Standard precautions

### General  

- keep samples on ICE at all times  

- always use disposable gloves (but do not believe that they give much protection!)  

- observe scrupulous aseptic technique when making up solutions  

- store samples at -- 70deg  


### Equipment  

- ideally set aside glassware, plasticware and buffers for exclusive use in RNA experiments  

- only use freshly-opened plastic-ware (pipette tips, eppendorfs, Falcon tubes etc.); use filter-tip pipette tips  

- spray work-tops, plasticware and pipettors liberally with RNAse-away  

- ideally treat glassware by baking for 4 hrs @ 300 deg)  

- treat pipettors by disassembling and soaking the plastic in 3 % H~2~O~2~ prior to use (ideally keep a separate set for RNA work)  

- prepare electrophoresis tank as follows:  

    - clean with detergent, rinse with H2O, dry with EtOH, treat with 3% H~2~O~2~ for 10 mins @ RT...  
    - ...then rinse with DEPC water (ideally keep a separate tank for RNA work)  


## Solutions

```{block2, type='note'}
DEPC can be used in most aqueous solutions including PBS and MOPS but NOT Tris or HEPES buffers. Therefore make Tris or HEPES up in
DEPC-treated water (rather than by adding DEPC to the buffer). Autoclaving should remove residual DEPC. This is important because DEPC
can react with adenine (carboxymethylation) and interefere with downstream applications.

```

- store solutions in small aliquots and discard each after use (i.e. do not use general lab stock solutions)  
- treat solutions with 0.1 % DEPC (= 100 mcl in 100 ml) @ RT overnight then autoclave  
- treat water with 0.01 % DEPC (= 100 mcl in 1L) @ RT overnight then autoclave  
