# Western blot

## Materials

- 7 mm steel beads (Qiagen 69990)  
- Merck III PIC (535140)  
- isolation buffer (250 mM sucrose, 10 mM triethanolamine, pH 7.6, F.S.)  
- DTT (500 mM in aq)  
- tris-glycine buffers: sample buffer (LC2676), running buffer (LC2675), transfer buffer (LC3675)  
- tris-glycine gels (e.g. Novex Wedge-Well 4 -- 12%, 15 lanes)   
- PageRuler ladder (26619)  
- PVDF membrane (LC2005) 
- wash buffer = 0.2% Tween in PBS (= 2 ml in 1L)  
- block buffer = 5% (w/v) milk powder (= 2g in 40 ml)   
- ECL (34577)  
- Instant Blue (ab119211)

<br>
<br>

## Method: protein extraction

i\) place tissue (e.g. half kidney) in 2 ml eppendorf and thaw on ice  
ii\) add c. 1.5 ml ice-cold isolation solution with 1% PIC (15 mcl)     
iii\) homogenise, ensuring stays ice-cold   
iv\) incubate on ice for 15'  
v\) spin @ 4000 g for 15' at 4deg  
vi\) dilute 1:10 in aq for BCA assay  

<br>

*NB If half a kidney is 100 mg then would require approximately 5 mcl of PIC - so above is conservative.*

<br>
<br>



## Method: blot

### Prepare samples  

- sample = 16 mcl  
- 2x sample buffer = 20 mcl  
- 500 mM DTT = 4 mcl  
- ...therefore total = 40 mcl with final 50 mM DTT  

Heat to 70deg for 15 mins (NB do NOT heat ladder).  

<br>
<br>


### SDS-PAGE  

i\) make 1L buffer for two chambers  
ii\) rinse wells and load as per reference card  
iii\) run @ 225V for 30 -- 45 mins  

<br>
<br>

### Transfer 

i\) make up 500 ml transfer buffer for one gel = 20 ml of 25x concentrate, 100 ml MeOH (= 20%)  
ii\) soak pads in transfer buffer  
iii\) pre-wet PVDF in MeOH for 30 secs then rinse in aq and soak in TB for a few mins  
iv\) do NOT equilibrate gel in TB  
v\) pre-wet filter paper  
vi\) assemble as per quick reference card (remember wet cathode with 10 ml TB first and smooth with roller after each step)  
vii\) transfer on Mini Blot module @ 20V for 60 mins. 
viii\) wash with 20 ml aq for 5 mins x2  

<br>

*NB At this point can do Coomassie Blue staining and annotate membrane with xylene-resistant histology pen.  Can dry to pause (see below.)  Need to rehydrate into MeOH before blotting.*  

<br>
<br>

### Blot

i\) block for 40 mins @ RT  
ii\) 1ry Ab overnight @ 4deg  
iii\) wash x 5 mins x 3  
iv\) 2ry Ab for 60 mins @ RT  
v\) wash x 10 mins x 3  
vi\) ECL > LICOR Odyssesy

*NB can preserve 1ry Ab with 0.05% NaN3 (= 250 mcl of 1% into 5 ml).*  

<br>

*NB can store blot by washing in 100% MeOH then air-drying on 3MM paper until bone dry.  Store in zip-lock bag with air squeezed out at 4deg for decades.*  

<br>
<br>

### Post-stain 

i\) wash x 5 mins x 3 with water  
ii\) stain with Coomassie Blue for 5 mins. 
iii\) destain in 50% MeOH (or 50% MeOH / 7% acetic acid?) for a few mins  
iv\) image on IR channel 

