# Safety

-   decontaminate all virus-containing medium / plasticware with 1%
    virkon for 24 hrs and then autoclave (1 hr is probably sufficient
    but RA says 24 hrs)

-   culture cells in virus suite until second wash after transduction

# Methods

-   transduce at subconfluency (e.g. 30 -- 70 %)

-   use Polybrene @ 1:1000 (= final 10 mcg per ml)

-   try MOI 1:1 -- 1:100 (but usually anything \> 1:50 will induce cell
    death)

-   24 hrs after transduction, wash cells twice and discard medium into
    virkon (as above)

-   start selection 2 -- 3 days post-transduction

-   from my kill curves in hPodo AB, appropriate selection would be:

    -   blasticidin (Merck US1203351) @ 45 mcg/ml

    -   puromycin(Merck US1540411) @ 1.5 mcg/ml

# Specific methods for my constructs

-   optimum viral "load" in hPodos as assessed using emGFP = 6.5 × 10^6^
    TU per T25 flask at 30% confluence (\~ MOI 50) = \~3.3 ×10^7^ TU if
    assessing titre by Q-PCR (rather than fluorescence)

-   volume of virus required to deliver 3.3 ×10^7^ TU =

    -   LV-HA-UPRT (8.3 ×10^6^ TU/mcl) = 4.0 mcl -- therefore use 5 mcl

    -   LV-Ago2 (3.0 ×10^6^ TU/mcl) = 11.0 mcl -- therefore use 10 mcl

    -   LV-emGFP-CD9 (4.8 ×10^6^ TU/mcl) = 6.9 mcl -- therefore use 5
        mcl

-   selection =

    -   LV-HA-UPRT: blasticidin

    -   LV-Ago2: puromicin

    -   LV-emGFP-CD9: blasticidin

    -   ...and remember CONTROL flasks
